"""add_gateway_fleet_columns

Revision ID: 418fc659954a
Revises: 140331002ece
Create Date: 2026-02-24 04:41:03.860925+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "418fc659954a"
down_revision = "140331002ece"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("run_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True)
        )
        batch_op.add_column(sa.Column("fleet_ssh_private_key", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("fleet_ssh_public_key", sa.Text(), nullable=True))
        batch_op.alter_column(
            "backend_id",
            existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        )
        batch_op.create_index(batch_op.f("ix_gateways_run_id"), ["run_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_gateways_run_id_runs"), "runs", ["run_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_gateways_run_id_runs"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_gateways_run_id"))
        batch_op.alter_column(
            "backend_id",
            existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        )
        batch_op.drop_column("fleet_ssh_public_key")
        batch_op.drop_column("fleet_ssh_private_key")
        batch_op.drop_column("run_id")

    # ### end Alembic commands ###
