type: task
# The name is optional, if not specified, generated randomly
name: axolotl-multi-node

# Size of the cluster
nodes: 2

image: nvcr.io/nvidia/pytorch:25.01-py3

# Required environment variables
env:
  - HF_TOKEN
  - ACCELERATE_LOG_LEVEL=info
  - WANDB_API_KEY
  - NCCL_DEBUG=INFO
  - CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
  - WANDB_NAME=axolotl-dist-llama-qlora-train
  - WANDB_PROJECT
  - HUB_MODEL_ID=meta-llama/Meta-Llama-3-70B
# Commands of the task
commands:
  # axolotl installation removes the existing torch, and installs torch 2.4 with axolotl 0.5
  - pip uninstall torch -y
  - pip uninstall flash-attn -y
  - pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/test/cu124
  - pip install --no-build-isolation axolotl[flash-attn,deepspeed]
  - pip install flash-attn --no-build-isolation
  - wget https://raw.githubusercontent.com/huggingface/trl/main/examples/accelerate_configs/fsdp1.yaml
  - wget https://raw.githubusercontent.com/axolotl-ai-cloud/axolotl/main/examples/llama-3/qlora-fsdp-70b.yaml
  - pip uninstall hf-xet -y
  - accelerate launch --config_file=fsdp1.yaml -m axolotl.cli.train qlora-fsdp-70b.yaml --hub-model-id $HUB_MODEL_ID --output-dir /checkpoints/qlora-llama3-70b --wandb-project $WANDB_PROJECT --wandb-name $WANDB_NAME
    --main_process_ip=$DSTACK_MASTER_NODE_IP
    --main_process_port=8008
    --machine_rank=$DSTACK_NODE_RANK
    --num_processes=$DSTACK_GPUS_NUM
    --num_machines=$DSTACK_NODES_NUM
  

resources:
  gpu:
    # 24GB or more VRAM
    memory: 80GB..
    # One or more GPU
    count: 8
  # Shared memory (for multi-gpu)
  shm_size: 24GB

volumes:
  - /checkpoints:/checkpoints
