# Not Working
type: dev-environment
name: deepseek-v2-lite-nvidia

image: lmsysorg/sglang:latest
env:
  - MODEL_ID=deepseek-ai/DeepSeek-V2-Lite
init:
  - python3 -m sglang.launch_server
    --model-path $MODEL_ID
    --port 8000
    --trust-remote-code
    --max-total-tokens 4096

# port: 8000

# model: deepseek-ai/DeepSeek-V2-Lite
ide: vscode

resources:
  gpu: 48GB
