type: dev-environment
# The name is optional, if not specified, generated randomly
name: trl-grpo-vscode

# If `image` is not specified, dstack uses its default image
python: "3.10"


ide: vscode

# Uncomment to leverage spot instances
#spot_policy: auto

resources:
  gpu:
    # 24GB or more vRAM
    memory: 24GB
    # One or more GPU
    count: 1
